### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-block-ui'

### ISSUE THREAD

**Issue by UX-Unicorn** [Availity/react-block-ui#1]
I installed react-block-ui but webpack is unable to load it.  It is looking for it in node_modules but there is no index.js file installed?  
Here is my import statement:
 import BlockUi from 'react-block-ui';

This the file structure that gets downloaded for react-block-ui
react-block-ui/
    node_modules/
    License
    package.json
    README.md
    redux.js

Is there more that should be downloaded?  How can I fix this error?

Thanks in advance

**Comment by TheSharpieOne** [comment]
Sorry about that. The version published to npm did not include the generated lib. I have pushed a new version; 0.2.2. Please use that.

**Comment by robmcguinness** [comment]
@TheSharpieOne can you push up tag to Github as well?

**Comment by TheSharpieOne** [comment]
Done

**Comment by UX-Unicorn** [comment]
Thanks
