### ISSUE TITLE
setImmediate() is a non-standard function

### ISSUE THREAD

**Issue by benpptung** [Availity/react-block-ui#11]
Hi...got an Reference Error today, and found this is because setImmedaite() got called in componentWillReceiveProps(). can you fix it, I really like react-block-ui :)

**Comment by TheSharpieOne** [comment]
Eh, I figured that thing would be a thing by now (and I thought it was seeing how nodejs has it which I thought meant chrome did as well), but it looks like [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=146172) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=686201) don't like it for various "reasons" (very longs issue threads...). It is a standard, just an [unofficial one](http://w3c.github.io/setImmediate/) which looks like will it never make it pass the editor's draft phase.
We use drafts all of the time (though usually working drafts) and depend on polyfills and transforms to allow us to use them.
Also, if you are using react, you are already including a polyfill for `setImmediate` via: [setimmdeite](https://www.npmjs.com/package/setimmediate) <- [fbjs](https://github.com/facebook/fbjs/blob/8ebe17be43eb73bbff1e04ddb2b1a3d9279cfa57/packages/fbjs/package.json#L68) <- [react](https://github.com/facebook/react/blob/79074a805994ed1ff9d2a80e502490f0d67f2702/packages/react/package.json#L25)

That being said, I'm going to make it so `setImmediate` doesn't need to be defined. (`(window.setImmediate || setTimeout)(() => this.topFocus && this.topFocus.focus());` will probably work best)

**Comment by benpptung** [comment]
I am using react, but I don't use the polyfill,  I guess this is why I got that error. :) 
Thank you for your reply, I've solved it already.

**Comment by TheSharpieOne** [comment]
I am not 100% sure how you are not using the polyfill since it is included with react via react's dependencies. Maybe treeshaking is removing it?

**Comment by benpptung** [comment]
I've been looking into React's code, and React doc website [https://facebook.github.io/react/docs/hello-world.html](url), and I think React doesn't include `setImmediate`, because

1. If we open the browser's console, type `typeof setImmediate` on the React website, it is `undefined`. It means no `setImmediate` exist in global, even React exist.

2. And it seems React doesn't `require` setImmediate from fbjs to attach it to global.

So, you can find setImmediate in the global scope? ...mmm ... weird  :)

**Comment by TheSharpieOne** [comment]
I have never used react with UMD imports and script tags like that, it appears they have a special build which probably helps minimize the size. https://github.com/facebook/react/blob/2fa38ac1cce658ce799a162e65fcf782187c8802/scripts/rollup/modules.js#L188-L196

**Comment by benpptung** [comment]
Yes ... :) I am still using `require`, and using browserify to bundle react.

so, if we cannot guarantee `setImmediate()` exist in global scope, I suggest to use `setTimeout({fn}, 0)`, which should always works across browsers and server-rendering.
