### ISSUE TITLE
react-block-ui doesn't work with Nextjs

### ISSUE THREAD

**Issue by poornachandugade** [Availity/react-block-ui#19]
even with the state having {blocking : true} all child components were accessible to interact

**Comment by TheSharpieOne** [comment]
Do you have a minimal viable example (such as an online sandbox or a sample repo) to help me reproduce this?

**Comment by TheSharpieOne** [comment]
@poornachandugade were you able to resolve the issue?

**Comment by poornachandugade** [comment]
No.Without a deeper understanding of nextjs i can not comment any further. So I switched to simple loaders instead of block-ui where we don't need to import css files seperately.
