### ISSUE TITLE
keepInView no more working

### ISSUE THREAD

**Issue by LouisCuvelier** [Availity/react-block-ui#21]
Hi,

Thanks for the lib, but `keepInView` is no more working on 1.1.3.

Can you do something please ?

**Comment by TheSharpieOne** [comment]
I am not able to reproduce. Please take a look at https://stackblitz.com/edit/react-block-ui-keepinview?file=Example.js

**Comment by LouisCuvelier** [comment]
That's strange, for my part, it's working now. I maybe messed up the CSS for a while.
Thanks for your help and I'm very sorry for the disturbance 😔

**Comment by TheSharpieOne** [comment]
No worries. Thanks for using this lib!

**Comment by sanju-developer** [comment]
what new you have done in this, so this is working :)
