### ISSUE TITLE
Installing package on version 1.1.4 is not exposing css and redux files at the root folder. Version 1.1.3 works fine.

### ISSUE THREAD

**Issue by azinod** [Availity/react-block-ui#30]
### Current behavior
Installing the package at version 1.1.4 is not exposing the redux and css files on the root folder. Consequently, importing **react-block-ui/redux'**, **react-block-ui/reduxMiddleware** and **react-block-ui/style.css** fails.

Installing the package at version 1.1.3 exposes the files at the root folder as expected.
### Expected behavior
Files should be exposed so I can import them as shown in the docs.
### Steps to recreate the problem
1. Create a new node project (**npm init -y**)
2. Install package: **npm install react-block-ui**
3. Check package files in the **node_modules** folder 

### Environment
- Windows 10 Professional
- NodeJS 6.13.1 (legacy system)
- npm 5.6.0

**Comment by TheSharpieOne** [comment]
The files are missing from the published package.
https://unpkg.com/react-block-ui@1.1.4/
https://unpkg.com/react-block-ui@1.1.3/

**Comment by brenopolanski** [comment]
I solved by putting the `lib/` folder.

**Example**:

`import ReduxBlockUi from 'react-block-ui/lib/redux';`

**Comment by GoPro16** [comment]
From what I am seeing, it looks like those files are not being copied over in the build/release script. Going to open a PR to get those added over.

**Comment by GoPro16** [comment]
fixed in `v1.3.1`

`/redux` works again. or `/lib/redux`.
