### ISSUE TITLE
Could not find type declaration for module react-block-ui

### ISSUE THREAD

**Issue by rrdlpl** [Availity/react-block-ui#34]
My project is written in typescript and I can't use this component.

By importing the library in my component I get the following error:

![Screenshot from 2019-07-31 10-30-56](https://user-images.githubusercontent.com/1158120/62196524-80394980-b37e-11e9-9ec6-1aaff21ef007.png)

Version: 1.1.3 - 1.1.4

**Comment by GoPro16** [comment]
If `types` don't exist for any library you are installing you can simply add it something by declaring it like

```typescript
declare module 'react-block-ui' {
 // definitions here
}
```

#24 is supposed to fix this but needs work.

**Comment by rrdlpl** [comment]
Hi @GoPro16  I created the PR with the comments on the #24 
Thanks for your help.

**Comment by GoPro16** [comment]
Closed via #36 

As a heads up I did have to fix one minor [issue](https://github.com/Availity/react-block-ui/commit/ea4dc7d865a7e57cb023844603b8ea4be371e33e)

`v1.3.0` released
