### ISSUE TITLE
Typings problem with tag prop

### ISSUE THREAD

**Issue by domehead100** [Availity/react-block-ui#41]
Just tried upgrading to latest, and we're getting typescript errors with the tag="div" prop:
```typescript
Type 'string' is not assignable to type '{(...args: any[]) => any) & string'.  ts(2322)
```
The problem seems to be that in reactblockui.d.ts:
```typescript
tag?: (...args: any[]) => any | string,
```
should be:
```typescript
tag?: ((...args: any[]) => any) | string,
```
(note the parens around the entire expression before the or operator)

**Comment by GoPro16** [comment]
Feel free to submit a PR

**Comment by TheSharpieOne** [comment]
This this resolved with the link PR above? If so, please feel free to close the issue.

**Comment by domehead100** [comment]
Yep.  Thanks.
