### ISSUE TITLE
reduxMiddleware examples/documentation wrong?

### ISSUE THREAD

**Issue by mpmeyer** [Availity/react-block-ui#43]
The examples and doc show:
import reduxMiddleware from 'react-block-ui/reduxMiddleware';

Should be:
import reduxMiddleware from 'react-block-ui/lib/reduxMiddleware';

thx

**Comment by TheSharpieOne** [comment]
The latest release is messed up as noticed in https://github.com/Availity/react-block-ui/issues/30#issuecomment-506763773
At this point, it's probably just easier to suggest using `react-block-ui/lib/reduxMiddleware` (it's just 4 more characters, not a big deal). The docs need updated.
