### ISSUE TITLE
Unable to improve reduxMiddleware from react-block-ui/reduxMiddleware

### ISSUE THREAD

**Issue by SunWeiJunnnnn** [Availity/react-block-ui#50]
When I import `reduxMiddleware `, save the change
```
// ./index.js
import reduxMiddleware from "react-block-ui/reduxMiddleware";

```

A compile error comes out :

**Failed to compile.**
**./src/index.js**
**Module not found: Can't resolve 'react-block-ui/reduxMiddleware' in 'myprojectdir\src'**

react : 16.12.0
redux : 4.0.4
react-block-ui: 1.3.2

I really hope someone could tell me why and how can I fix this. thanks.

**Comment by TheSharpieOne** [comment]
you're going to have to import it from `lib/`, some of the helper files (which just make it easier to import by not needing `lib/`) did not get generated in the latest release: 
```
import reduxMiddleware from "react-block-ui/lib/reduxMiddleware";
```

**Comment by SunWeiJunnnnn** [comment]
> you're going to have to import it from `lib/`, some of the helper files (which just make it easier to import by not needing `lib/`) did not get generated in the latest release:
> 
> ```
> import reduxMiddleware from "react-block-ui/lib/reduxMiddleware";
> ```

you have solved my promble, thank you
