### ISSUE TITLE
react-block-ui throwing error in my tests

### ISSUE THREAD

**Issue by asfernandes** [Availity/react-block-ui#6]
When I test my component with jest, enzyme and enzyme-to-json, react-block-ui is randomly throwing an error in the new focus-control code.

```
 PASS  src\components\__tests__\ErrorMessage.test.tsx
 PASS TypeError: Cannot read property 'focus' of null
    at Immediate.<anonymous> (C:\Projeto\v2-react\SIMM\node_modules\react-block-ui\lib\BlockUi.js:93:37)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

It will be difficult for me to create a minimal test case.

Maybe some null-check in react-block-ui will solve the issue.

**Comment by TheSharpieOne** [comment]
What version are you using? Additional null checks were added in 0.2.4 after #5 which looks for be the same issue and was resolved by the new version

**Comment by asfernandes** [comment]
I was using 0.2.3 and didn't verified for new version before report, sorry.
