### ISSUE TITLE
Default loader being used

### ISSUE THREAD

**Issue by alex-holt** [Availity/react-block-ui#7]
I'm finding the default loader isn't being overridden by my chosen loading component, here's my code: 

```
<BlockUi blocking={isLoading} loader={<FontAwesome size="2x" name="spinner" pulse />}>
    {wrapped components}
</BlockUi>
```

What I'm seeing is the default (3 dots) loader sitting underneath the BlockUi wrapped components when the loading state is set. 

Everything else works fine.

Anything I'm missing here?

**Comment by TheSharpieOne** [comment]
Make sure you have the latest version.
I didn't want to have to deal with importing FontAwesome, but here is this: http://www.webpackbin.com/4kK2-1UYM

**Comment by TheSharpieOne** [comment]
@alex-holt Can you confirm you are using the latest version (0.2.4)?

**Comment by TheSharpieOne** [comment]
Webpackbin released a completely new version. See this updated bin: https://www.webpackbin.com/bins/-KeooKtE8HIypIzTF4Xk

Closing as a non-issue. If you have any further information to reproduce the issue, please reopen.
