### ISSUE TITLE
error when using react component as tag

### ISSUE THREAD

**Issue by blacktemplar** [Availity/react-block-ui#8]
Until now I could use BlockUI with a React component as tag and it worked out as expected, but since the latest update I get the following error:

this.wrapper.contains is not a function in file BlockUi.js:89

I debugged it a little bit and saw that there it is expected that this.wrapper is a DOM element to be able to call the contains function. But if tag was a React component this.wrapper will be a react component and won't have a contains function.

I am not sure if you want to allow React components as tags or not but if you want to allow them this bug should be fixed. In the meantime I went back to using "div" as tag and everything works now.

**Comment by TheSharpieOne** [comment]
The code needs to have access to the wrapping component to determine if any element within it has focus. It does this to determine if focus should be removed when blocking starts.
The tag was intended to be used as you are using it, allowing for any component to be used.
The simplest solution here would be to restrict the focus management feature to when `tag` is a strings... but that would suck.

**Comment by TheSharpieOne** [comment]
I added a helper element which I can use to dynamically get the wrapping element from to determine focus. This should resolve your issue.

**Comment by GoPro16** [comment]
@TheSharpieOne I'm not sure if your help resolved this issue. I created a code sandbox link as an example of this error still persisting only on the first load since the ref doesn't exist yet. After that, "during development" on react hot reloads the error doesn't re-pop up.

https://codesandbox.io/s/7jw0k58j41

**Comment by TheSharpieOne** [comment]
Apparently I broke this with this commit: https://github.com/Availity/react-block-ui/commit/7ba8b8e660b1aafa53b5fab27f0fb34f2c143e4e
I added a `ref` back to the wrapping component where `Tag` is used :(

**Comment by MrSpoocy** [comment]
#26
